version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - myRedis:/data

  pg:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: eCom
      POSTGRES_PASSWORD: eCom
      POSTGRES_DB: eCom
    ports:
      - 5433:5432
    volumes:
      - myDb:/var/lib/postgresql/data

  ecommerce:
    build:
      context: .
      dockerfile: ./DockerFile
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  myRedis:
  myDb:
